import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Contact from '../components/Contact'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Resume from '../components/Resume'
import Showreel from '../components/Showreel'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="scroll-smooth bg-neutral-50 text-neutral-700 h-screen snap-y snap-mandatory overflow-scroll z-0 scrollbar  scrollbar-thumb-neutral-900 scrollbar-track-transparent">
      <Head>
        <title>Issak Hindson </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

    <section id="hero" className='snap-start'> 
     <Hero />
    </section>

    <section id="showreel" className='snap-center'>
      <Showreel />
    </section>

    <section id="projects" className='snap-center'>
      <Projects />
    </section>

    <section id="about" className='snap-center'>
        <About />
    </section>
      
    <section id="resume" className='snap-center'>
        <Resume />
    </section>

  
    <section id="contact" className='snap-center'>
      <Contact />
    </section>



      </div>
  )
}

export default Home
